version: 2.1
jobs:
  compile:
   docker:
      - image: z4nyx/docker:latest
   steps:
      - run:
          command: |
           git config --global user.name "Tooya12"
           git config --global user.email "whatistooya12@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://github.com/Tooya12/kernel_xiaomi_lavender-New .
           bash .circleci/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
